const Contents = {
  about: {
    link: "About Me",
    name: "My name is Hadi.",
    title: "I’m a FrontEnd Developer based in Vancouver.",
    desc: "I'm a passionate and dedicated UI/UX designer with a strong focus on creating exceptional user experiences. I thrive on transforming complex ideas into intuitive and visually appealing designs. With a keen eye for detail and a user-centered approach, I strive to deliver impactful solutions that engage and delight users. Let's collaborate to bring your digital products to life!",
    skills: "Here are a few technologies I've been working with recently:",
  },

  navList: [
    ["plumbing", "Minor Plumbing"],
    ["electrician", "Minor Electrician"],
    ["carpentry", "Minor Carpentry"],
    ["doorwindow", "Doors and Windows"],
    ["wallfloor", "Wall and Floor"],
    ["painting", "Painting and Staining"],
    ["mounting", "Mountings and Assemblies"],
    ["senior", "Seniors Safety and Mobility"],
  ],
  carNavList: [
    ["cardetail", "Car Washing and Detailing"],
    ["carrepair", "Car Repair and Maintenance"],
  ],

  INTRO:
    "I'm a Burnaby-based handyman specializing in providing reliable home and vehicle services in assembling, mounting and repair.",

  plumbing: {
    id: 1,
    title: "Minor Plumbing.",
    services: [
      "Faucet.",
      "Kitchen Sink.",
      "Garbage Disposals.",
      "Toilet.",
      "Bath Tube.",
      "Pipe Insulation.",
    ],
    images: [
      "Plumbing-Faucet",
      "Plumbing-KitchenSink",
      "Plumbing-GarbageDisposal",
      "Plumbing-Toilet",
    ],
  },
  electrician: {
    id: 2,
    title: "Minor Electrician.",
    services: [
      "Wall & Light Switches.",
      "Power Outlets.",
      "Safety Outlet.",
      "Tamper Resistant Outlet.",
      "Light Fixtures.",
      "Motion Sensors.",
      "Bulb Changes.",
      "Smart Home Devices.",
      "Door Bells.",
      "Smoke Detectors.",
      "Bathroom exhaust fan.",
    ],
    images: [
      "electrition-switche",
      "electrition-light-ficture",
      "electrition-motion-sensor-light-on",
      "electrition-motion-sensors",
      "electrition-bulbchange",
      "electrition-smoke-detector",
      "electrition-bathroom-exhaust-fan",
      "electrition-smart-homes",
    ],
  },
  carpentry: {
    id: 3,
    title: "Minor Carpentry.",
    services: [
      "Wood repairs.",
      "Cabinet.",
      "Sink Bottom.",
      "Handrails and Stairs.",
      "Exterior Fence.",
      "Closet & garage Shelving.",
      "Deck and Patio.",
    ],
    images: [
      "carpentry-Wood repairs",
      "carpentry",
      "carpentry-cabinet",
      "carpentry-Sink Bottom",
      "carpentry-Handrails and Stairs",
      "carpentry-Exterior Fence",
      "carpentry-Closet & garage Shelving",
      "carpentry-deck & pattio",
    ],
  },
  doorwindows: {
    id: 4,
    title: "Doors and Windows.",
    services: [
      "Interior/Exterior doors.",
      "Garage doors.",
      "Storm doors.",
      "Sliding doors & Windows.",
      "Rescreen sliding doors.",
      "Door knobs & deadbolts.",
      "Bathtub & Shower Doors .",
      "Exterior Gates.",
      "Security & Keyless Entry.",
    ],
    images: [
      "DW-extrior-door",
      "DW-sliding-door",
      "DW-sliding-window",
      "DW-door-window-screen",
      "DW-Bathtub-Shower-Doors",
      "DW-Security-Keyless-Entry",
    ],
  },
  WallFloor: {
    id: 5,
    title: "Wall and Floor.",
    services: [
      "Floor and Wall Tile.",
      "Bathroom Caulking.",
      "Vinyl & Laminate Floor.",
      "Drywall.",
    ],
    images: [
      "WF-Laminate-Floor-Repair",
      "WF-vinyl-floor-repair",
      "WF-Caulking-Bathtub-Shower",
      "WF-Drywallwall-repair",
          ],
  },
  PaintingStaining: {
    id: 6,
    title: "Painting and Staining.",
    services: [
      "Walls.",
      "Doors & Windows.",
      "Furniture.",
      "Decks.",
      "Cabinets.",
    ],
    images: [
      "PS-Wall-painting",
      "PS-exteriordoor-painting",
      "PS-stain-door",
      "PS-painting-deck",
      "PS-deck-staining",
      "PS-Cabinet-Painting",
    ],
  },
  MountingsAssemblies: {
    id: 7,
    title: "Mountings and Assemblies.",
    services: [
      "Child Proofing.",
      "Picture Hanging.",
      "TV Wall Mounting.",
      "Curtains & Drapes.",
      "Hanging Blinds.",
      "Filters Replacement.",
      "Kitchen Appliance.",
      "Showers, Toilet Bars.",
      "Metal Stairs.",
      "Shower glass Door.",
      "Furniture Assembly.",
      "IKEA Furniture.",
      "Pet House.",
      "Storage Racks.",
      "Bikes.",
    ],
    images: [
      "MA-Child Proofing",
      "MA-Picture Hanging",
      "MA-TV_mounting",
      "MA-Hang_Curtains",
      "MA-hanging blinds",
      "MA-filter",
      "MA-kitchen applience",
      "MA-grab-bars",
      "MA-Metal stairs",
      "MA-IKEA",
      "MA-Closet-garage-Shelving",
      "MA-Metal stairs",
    ],
  },
  seniorsMobility: {
    id: 8,
    title: "Modifications for Seniors Safety and Mobility.",
    services: [
      "Widen Doorways & Ramp Installation.",
      "Grab bars & Handrails.",
      "Simplify Kitchen Layout.",
      "Modify Bath & bedroom.",
      "Upgrade Door Handles.",
      "Lowering Rod for Shelves and Closets.",
    ],
    images: [
      "MS-Ramp Installation",
      "MS-Ramp Installation-1",
      "MS-Ramp Installation-2",
      "MS-Grab barsHandrails",
      "MS-Grab barsHandrails-1",
      "MS-Grab barsHandrails-2",
      "MS-Upgrade Door Handles",
      "MS-Upgrade Door Handles-1",
      "MS-Lowering Rod for Shelves and Closets",
      "MS-Lowering Rod for Shelves and Closets-1",
    ],
  },
  carDetailing: {
    id: 8,
    title: "Car Washing and Detailing.",
    services: [
      "Power washing.",
      "Deep Cleaning.",
      "Buffing and Waxing.",
      "Vacuuming.",
      "Foggy headlight cleaning.",
    ],
    images: [
      "CD-Power washing",
      "CD-Power washing-1",
      "CD-vaccuming",
      "CD-Deep Cleaning",
      "CD-buffing",
      "CD-Foggy headlight cleaning",
    ],
  },
  carRepair: {
    id: 8,
    title: "Car Repair and Maintenance.",
    services: [
      "Oil and Filter changes.",
      "Headlight and Taillight bulb.",
      "Engine flush.",
      "Brake pads and rotors.",
      "Installing backup camera.",
      "Winter tire swap.",
      "Spark plugs.",
      "Spare tire installation.",
      "Dead battery.",
      "Minor mechanical repairs.",
    ],
    images: [
      "CR-oil-change",
      "CR-Filter changes",
      "CR-Brake pads and rotors",
      "CR-Engine flush",
      "CR-Backup-camera-on-a-vehicle",
      "CR-Car light bulb change",
      "CR-car-brake-light-for-replacement-scaled",
      "CR-spark-plugs-replacement",
      "CR-Car-Battery change",
      "CR-Winter-Tires swap",
    ],
  },
};

export default Contents;
